<?
$PERM["lichnyy-kabinet-pokupatelya"]["2"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["9"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["7"]="X";
$PERM["lichnyy-kabinet-pokupatelya"]["8"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["10"]="X";
$PERM["lichnyy-kabinet-pokupatelya"]["6"]="R";
$PERM["lichnyy-kabinet-pokupatelya"]["*"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["2"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["9"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["7"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["8"]="X";
$PERM["lichnyy-kabinet-prodavtsa"]["10"]="X";
$PERM["lichnyy-kabinet-prodavtsa"]["6"]="R";
$PERM["lichnyy-kabinet-prodavtsa"]["*"]="D";
$PERM["search"]["6"]="W";
$PERM["products"]["6"]="W";
$PERM["services"]["6"]="W";
$PERM["news"]["6"]="W";
$PERM["contacts"]["6"]="W";
$PERM["company"]["6"]="W";
$PERM["index.php"]["6"]="W";
$PERM["/"]["*"]="R";
?>